package com.awsbedrock.api.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * ============================================================
 * Job Entity — Maps to the linkedin_naukr_jobs.jobs Table
 * ============================================================
 *
 * This JPA entity maps directly to your MySQL table:
 *   SELECT * FROM linkedin_naukr_jobs.jobs;
 *
 * TABLE STRUCTURE:
 * ┌──────────────────────────────┬───────────────┬───────────────────────────┐
 * │ Column                       │ Type          │ Example                   │
 * ├──────────────────────────────┼───────────────┼───────────────────────────┤
 * │ id                           │ BIGINT (PK)   │ 1                         │
 * │ title                        │ VARCHAR       │ "Java Full Stack Dev"     │
 * │ company                      │ VARCHAR       │ "TCS"                     │
 * │ location                     │ VARCHAR       │ "Bengaluru"               │
 * │ job_posted                   │ VARCHAR       │ "Posted: 1 day ago"       │
 * │ job_applyed_count_status     │ VARCHAR       │ "Applicants: 100+"        │
 * │ job_url                      │ VARCHAR       │ "https://naukri.com/..."  │
 * │ platform                     │ VARCHAR       │ "Naukri"                  │
 * │ description                  │ TEXT          │ "Job highlights..."       │
 * │ applied                      │ INTEGER       │ 0 or 1                    │
 * │ created_at                   │ TIMESTAMP     │ "2026-05-19 13:17:10"     │
 * └──────────────────────────────┴───────────────┴───────────────────────────┘
 *
 * JPA ANNOTATIONS EXPLAINED:
 *
 *   @Entity         → Marks this class as a JPA entity (maps to a DB table)
 *   @Table          → Specifies the table name and schema
 *   @Id             → Marks the primary key field
 *   @GeneratedValue → Primary key is auto-generated by the database
 *   @Column         → Maps a field to a specific DB column name
 *
 *   Note: If your Java field name matches the DB column name (camelCase
 *   to snake_case is automatic with Spring Boot's naming strategy),
 *   you don't need @Column. We use it here for clarity.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "jobs", catalog = "linkedin_naukr_jobs")
public class Job {

    /**
     * Primary key — auto-incremented by MySQL.
     * IDENTITY strategy means the DB generates the ID.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Job title — e.g., "Scala Developer", "Java Full Stack Developer"
     */
    @Column(name = "title")
    private String title;

    /**
     * Company name — e.g., "Tata Consultancy Services", "Quadrant Technologies"
     */
    @Column(name = "company")
    private String company;

    /**
     * Job location — e.g., "Bengaluru", "Hyderabad, Chennai, Bengaluru"
     */
    @Column(name = "location")
    private String location;

    /**
     * When the job was posted — e.g., "Posted: 1 day ago", "Posted: 3 weeks ago"
     */
    @Column(name = "job_posted")
    private String jobPosted;

    /**
     * Number of applicants — e.g., "Applicants: Less than 10", "Applicants: 100+"
     */
    @Column(name = "job_applyed_count_status")
    private String jobApplyedCountStatus;

    /**
     * Direct URL to the job posting on the platform
     */
    @Column(name = "job_url")
    private String jobUrl;

    /**
     * Platform where the job was scraped from — "Naukri", "LinkedIn"
     */
    @Column(name = "platform")
    private String platform;

    /**
     * Full job description text (can be very long).
     * @Column(columnDefinition = "TEXT") ensures JPA uses TEXT type in DDL.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Whether the user has applied (0 = not applied, 1 = applied)
     */
    @Column(name = "applied")
    private Integer applied;

    /**
     * Timestamp when the job record was created/scraped
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * Converts this Job entity into a concise text summary
     * suitable for sending to Bedrock as context.
     *
     * We don't send the raw HTML/description to save tokens and cost.
     * Instead, we create a structured summary the AI can easily parse.
     */
    public String toBedrockContext() {
        return String.format(
                "Job #%d: %s at %s | Location: %s | Posted: %s | Applicants: %s | Platform: %s | Applied: %s | URL: %s",
                id,
                title != null ? title : "N/A",
                company != null ? company : "N/A",
                location != null ? location : "N/A",
                jobPosted != null ? jobPosted : "N/A",
                jobApplyedCountStatus != null ? jobApplyedCountStatus : "N/A",
                platform != null ? platform : "N/A",
                applied != null && applied == 1 ? "Yes" : "No",
                jobUrl != null ? jobUrl : "N/A"
        );
    }
}
